#branches:
#  only:
#    - Android-Workspace 

language:
  - gcc 

env:
  global:
    - PV=r8e PLATF=linux-x86_64 NDK_HOME=${TRAVIS_BUILD_DIR}/android-ndk-${PV} PATH=${PATH}:${NDK_HOME}

# Change this to your needs
script:
  - java 

